CREATE TABLE lataus (
  lataustun SERIAL NOT NULL,
  saate TEXT,
  updated TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (lataustun));

CREATE TABLE atc (
  atctun INT NOT NULL,
  atckoodi VARCHAR(8) NOT NULL,
  selites VARCHAR(100) NOT NULL,
  seliter VARCHAR(100) NOT NULL,
  ddd VARCHAR(10) NULL,
  dddyksikko VARCHAR(5) NULL,
  PRIMARY KEY (atctun));


CREATE TABLE laakemuoto (
  laakemuototun INT NOT NULL,
  laakemuotonimi VARCHAR(75) NOT NULL,
  laakemuotonimir VARCHAR(75) NOT NULL,
  laakemuotonimie VARCHAR(75) NOT NULL,
  PRIMARY KEY (laakemuototun));
  

CREATE TABLE sailytysastia (
  astiatun INT NOT NULL,
  nimi VARCHAR(35) NOT NULL,
  nimie VARCHAR(35) NOT NULL,
  nimir VARCHAR(35) NOT NULL,
  PRIMARY KEY (astiatun));


CREATE TABLE maaraamisehto (
  ehtokoodi VARCHAR(4) NOT NULL,
  ehto VARCHAR(2000) NOT NULL,
  ehtor VARCHAR(2000) NOT NULL,
  PRIMARY KEY (ehtokoodi)); 


CREATE TABLE pakkaus (
  pakkausnro INT NOT NULL,
  vnrnro VARCHAR(6) NULL,
  pakkauskoko VARCHAR(20) NULL,
  kerroin BIGINT NULL,
  koko FLOAT NULL,
  yksikko VARCHAR(20) NULL,
  laite VARCHAR(50) NULL,
  astiatun INT NULL,
  kauppaantulopvm DATE NULL,
  kaupastapoispvm DATE NULL,
  reseptistatus VARCHAR(2) NOT NULL,
  laakenimi VARCHAR(64) NOT NULL,
  vahvuus VARCHAR(40) NULL,
  laakemuotonimi VARCHAR(75) NOT NULL,
  laakemuototun INT NOT NULL,
  haltija VARCHAR(61) NOT NULL,
  hum VARCHAR(1) NOT NULL,
  vet VARCHAR(1) NOT NULL,
  rinnakkaistuonti VARCHAR(1) NOT NULL,
  vaikainelkm INT NOT NULL,
  atckoodi VARCHAR(8) NULL,
  atctun INT NULL,
  ddd VARCHAR(10) NULL,
  dddyksikko VARCHAR(5) NULL,
  huume VARCHAR(2) NULL,
  psykoluokitus VARCHAR(3) NULL,
  liikennevaara VARCHAR(1) NULL,
  ehtokoodi VARCHAR(4) NULL,
  myyntilupanro INT NULL,
  eumyyntilupanro VARCHAR(100) NULL,
  paatospvm DATE NOT NULL,
  paattymispvm DATE NULL,
  tilanimi VARCHAR(45) NOT NULL,
  tilakoodi INT NOT NULL,
  muutos VARCHAR(12) NULL,
  edellinen_vnrnro VARCHAR(6) NULL,
  substituutioryhma VARCHAR(6) NULL,
  kaupan VARCHAR(1) NOT NULL,
  laakenimi_edellinen VARCHAR(64) NULL,
  maaraaikainen BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (pakkausnro),
  CONSTRAINT fk_pakkaus_maaraamisehto FOREIGN KEY (ehtokoodi) REFERENCES maaraamisehto(ehtokoodi),
  CONSTRAINT fk_pakkaus_atc FOREIGN KEY (atctun) REFERENCES atc(atctun),
  CONSTRAINT fk_pakkaus_laakemuoto FOREIGN KEY (laakemuototun) REFERENCES laakemuoto(laakemuototun),
  CONSTRAINT fk_pakkaus_sailytysastia FOREIGN KEY (astiatun) REFERENCES sailytysastia(astiatun));

CREATE TABLE pakkaus_pysyva (
  pakkausnro INT NOT NULL,
  vnrnro VARCHAR(6) NULL,
  pakkauskoko VARCHAR(20) NULL,
  kerroin BIGINT NULL,
  koko FLOAT NULL,
  yksikko VARCHAR(20) NULL,
  laite VARCHAR(50) NULL,
  astiatun INT NULL,
  kauppaantulopvm DATE NULL,
  kaupastapoispvm DATE NULL,
  reseptistatus VARCHAR(2) NOT NULL,
  laakenimi VARCHAR(64) NOT NULL,
  vahvuus VARCHAR(40) NULL,
  laakemuotonimi VARCHAR(75) NOT NULL,
  laakemuototun INT NOT NULL,
  haltija VARCHAR(61) NOT NULL,
  hum VARCHAR(1) NOT NULL,
  vet VARCHAR(1) NOT NULL,
  rinnakkaistuonti VARCHAR(1) NOT NULL,
  vaikainelkm INT NOT NULL,
  atckoodi VARCHAR(8) NULL,
  atctun INT NULL,
  ddd VARCHAR(10) NULL,
  dddyksikko VARCHAR(5) NULL,
  huume VARCHAR(2) NULL,
  psykoluokitus VARCHAR(3) NULL,
  liikennevaara VARCHAR(1) NULL,
  ehtokoodi VARCHAR(4) NULL,
  myyntilupanro INT NULL,
  eumyyntilupanro VARCHAR(100) NULL,
  paatospvm DATE NOT NULL,
  paattymispvm DATE NULL,
  tilanimi VARCHAR(45) NOT NULL,
  tilakoodi INT NOT NULL,
  muutos VARCHAR(12) NULL,
  edellinen_vnrnro VARCHAR(6) NULL,
  substituutioryhma VARCHAR(6) NULL,
  kaupan VARCHAR(1) NOT NULL,
  laakenimi_edellinen VARCHAR(64) NULL,
  PRIMARY KEY (pakkausnro),
  CONSTRAINT fk_pakkaus_m_maaraamisehto FOREIGN KEY (ehtokoodi) REFERENCES maaraamisehto(ehtokoodi),
  CONSTRAINT fk_pakkaus_m_atc FOREIGN KEY (atctun) REFERENCES atc(atctun),
  CONSTRAINT fk_pakkaus_m_laakemuoto FOREIGN KEY (laakemuototun) REFERENCES laakemuoto(laakemuototun),
  CONSTRAINT fk_pakkaus_m_sailytysastia FOREIGN KEY (astiatun) REFERENCES sailytysastia(astiatun));


CREATE TABLE pakkaus_maaraaikainen (
  pakkausnro INT NOT NULL,
  vnrnro VARCHAR(6) NULL,
  pakkauskoko VARCHAR(20) NULL,
  kerroin BIGINT NULL,
  koko FLOAT NULL,
  yksikko VARCHAR(20) NULL,
  laite VARCHAR(50) NULL,
  astiatun INT NULL,
  kauppaantulopvm DATE NULL,
  kaupastapoispvm DATE NULL,
  reseptistatus VARCHAR(2) NOT NULL,
  laakenimi VARCHAR(64) NOT NULL,
  vahvuus VARCHAR(40) NULL,
  laakemuotonimi VARCHAR(75) NOT NULL,
  laakemuototun INT NOT NULL,
  haltija VARCHAR(61) NOT NULL,
  hum VARCHAR(1) NOT NULL,
  vet VARCHAR(1) NOT NULL,
  rinnakkaistuonti VARCHAR(1) NOT NULL,
  vaikainelkm INT NOT NULL,
  atckoodi VARCHAR(8) NULL,
  atctun INT NULL,
  ddd VARCHAR(10) NULL,
  dddyksikko VARCHAR(5) NULL,
  huume VARCHAR(2) NULL,
  psykoluokitus VARCHAR(3) NULL,
  liikennevaara VARCHAR(1) NULL,
  ehtokoodi VARCHAR(4) NULL,
  myyntilupanro INT NULL,
  eumyyntilupanro VARCHAR(100) NULL,
  paatospvm DATE NOT NULL,
  paattymispvm DATE NULL,
  tilanimi VARCHAR(45) NOT NULL,
  tilakoodi INT NOT NULL,
  muutos VARCHAR(12) NULL,
  edellinen_vnrnro VARCHAR(6) NULL,
  substituutioryhma VARCHAR(6) NULL,
  kaupan VARCHAR(1) NOT NULL,
  laakenimi_edellinen VARCHAR(64) NULL,
  PRIMARY KEY (pakkausnro),
  CONSTRAINT fk_pakkaus_m_maaraamisehto FOREIGN KEY (ehtokoodi) REFERENCES maaraamisehto(ehtokoodi),
  CONSTRAINT fk_pakkaus_m_atc FOREIGN KEY (atctun) REFERENCES atc(atctun),
  CONSTRAINT fk_pakkaus_m_laakemuoto FOREIGN KEY (laakemuototun) REFERENCES laakemuoto(laakemuototun),
  CONSTRAINT fk_pakkaus_m_sailytysastia FOREIGN KEY (astiatun) REFERENCES sailytysastia(astiatun));

CREATE TABLE laakeaine (
  pakkausnro INT NOT NULL,
  ainetun INT NOT NULL,
  ainenimi VARCHAR(64) NULL,
  PRIMARY KEY (pakkausnro, ainetun),
  CONSTRAINT fk_laakeaine_pakkaus FOREIGN KEY (pakkausnro) REFERENCES pakkaus(pakkausnro));
